// Generated by CoffeeScript 1.6.3
/*
This file is meant to be an example for how to use the Volar player api.   
It contains 2 functions, initMC and getDuration.
When index.html is loaded, the file's onload event triggers initMC, which
binds event listeners to the volar embed in the page.
*/


(function() {
  var me;

  this.i = null;

  this.v = null;

  me = this;

  this.initMC = function() {
    var controls, debugdiv, debugprogress;
    debugdiv = document.getElementById('debug-info');
    debugprogress = document.getElementById('debug-progress');
    controls = document.getElementById('controls');
    me.i = document.getElementById('frame');
    me.v = new Volarvideo;
    me.v.connect(me.i);
    me.v.on('onComplete', function(data) {
      me.v.log('video completed');
    });
    me.v.on('onPublishMetaData', function(data) {
      return console.log(data);
    });
    me.v.on('onCurrentTimeChange', function(data) {
      var percent;
      debugdiv.innerHTML = "Current State: " + data.state + ", Total duration of video: " + data.duration + ", current position: " + data.position;
      percent = (data.position / data.duration) * 100;
      return debugprogress.style.width = percent + '%';
    });
    me.v.on('onMediaPlayerStateChange', function(data) {
      return controls.className = data.state;
    });
    me.v.duration(me.getDuration);
    me.v.play();
  };

  this.play = function() {
    return me.v.play();
  };

  this.pause = function() {
    return me.v.pause();
  };

  this.seek = function(seconds) {
    return me.v.seek(seconds);
  };

  this.getDuration = function(data) {
    return console.log("state is " + data.state + ", " + data.duration + " is the current duration, and the current position is " + data.position);
  };

}).call(this);
